project_name             = "twin"
environment              = "prod"
bedrock_model_id         = "us.amazon.nova-lite-v1:0"  # Use better model for production
bedrock_regions          = ["us-west-2", "us-east-1", "us-east-2"]
lambda_timeout           = 60
api_throttle_burst_limit = 20
api_throttle_rate_limit  = 10
use_custom_domain        = true
root_domain              = "modouktouray.com"  # Replace with your actual domain